### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by brightsider**
Improve Base Template, ListTemplate, TabBarTemplate
Add Now Playing

### CODE REVIEW

**Comment by birkir** [comment]
Is the Now Playing template working for you?

**Comment by brightsider** [comment]
Yes

**Comment by kkoscielniak** [comment]
@brightsider you probably could update the README.md as well

**Comment by birkir** [comment]
Awesome, LGTM.

**Comment by ForrestDWS** [comment]
@brightsider Cool! Excited to see this in the library. Is this implemented in the example project?

**Comment by brightsider** [comment]
@ForrestDWS sorry, I have no time for this

**Review by birkir — APPROVED** [review]

**Comment by ForrestDWS** [comment]
@brightsider no worries. I really appreciate you making this PR.  I'd really like to play with this. I've been trying to call `CarPlay.enableNowPlaying(true);` but my builds error out telling me that it isn't a valid function. Without it, I'm told that I cannot push CPNowPlayingTemplate in on its own. Can I take a look at what you are enabling for your .entitlements file? 
Ive got a screenshot of that error here in this thread https://github.com/birkir/react-native-carplay/issues/43

**Pull request merged**
